/** Contacts */
export const ADD_CONTACT = 'ADD_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const SAVE_CONTACT = 'SAVE_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const TOGGLE_SELECT_CONTACT = 'TOGGLE_SELECT_CONTACT';
export const TOGGLE_SELECT_ALL_CONTACT = 'TOGGLE_SELECT_ALL_CONTACT';
export const REMOVE_BULK_SELECTED = 'REMOVE_BULK_SELECTED';

/** Form */
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const SET_FORM_DATA = 'SET_FORM_DATA';